"""
detector.py
------------
Purpose: Detect suspicious activity using an UNSUPERVISED Isolation
Forest model (scikit-learn). Supports two modes:

  1. Synthetic Mode - trains instantly on logs/training_data.csv
     (generated by generate_data.py). Best for live demos.
  2. Live Mode - collects the server's OWN psutil metrics for a
     baseline period, then trains on that real data.

Isolation Forest works by randomly partitioning data; anomalies are
"isolated" in fewer splits than normal points, so they get a higher
anomaly score. This is well suited to cybersecurity telemetry because
we often don't have labeled attack examples in the real world.
"""

import os
import time
import joblib
import psutil
import pandas as pd
from sklearn.ensemble import IsolationForest

MODEL_PATH = os.path.join(os.path.dirname(__file__), "isolation_forest.joblib")
TRAINING_DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "logs", "training_data.csv")

# The numeric features the model is trained and scored on
FEATURE_COLUMNS = [
    "cpu_usage", "ram_usage", "disk_usage", "process_count",
    "failed_logins", "firewall_disabled",
    "network_bytes_sent", "network_bytes_recv", "usb_connected",
]


class ThreatDetector:
    """
    Wraps an Isolation Forest model with helper methods for training
    and scoring incoming client logs.
    """

    def __init__(self):
        self.model = None

    def train_synthetic(self):
        """
        Train the model instantly using the pre-generated synthetic
        dataset. Raises a clear error if generate_data.py hasn't been
        run yet.
        """
        if not os.path.exists(TRAINING_DATA_PATH):
            raise FileNotFoundError(
                "Training data not found. Run 'python server/generate_data.py' first."
            )

        df = pd.read_csv(TRAINING_DATA_PATH)
        X = df[FEATURE_COLUMNS].fillna(0)

        # contamination='auto' lets the model estimate the expected
        # proportion of anomalies itself; 100 trees is plenty for this
        # dataset size while staying fast enough for a live demo.
        self.model = IsolationForest(
            n_estimators=100, contamination=0.1, random_state=42
        )
        self.model.fit(X)
        joblib.dump(self.model, MODEL_PATH)
        print("[detector.py] Trained on synthetic data and saved model.")

    def train_live(self, duration_seconds: int = 600, sample_interval: int = 5):
        """
        Build a real baseline by sampling THIS machine's own psutil
        metrics for `duration_seconds` (default 10 minutes), then
        train the Isolation Forest on that baseline.

        This is slower but reflects the actual server hardware's
        normal behavior rather than synthetic assumptions.
        """
        print(f"[detector.py] Collecting live baseline for {duration_seconds}s...")
        samples = []
        elapsed = 0
        while elapsed < duration_seconds:
            samples.append(self._collect_live_sample())
            time.sleep(sample_interval)
            elapsed += sample_interval

        df = pd.DataFrame(samples)
        X = df[FEATURE_COLUMNS].fillna(0)

        self.model = IsolationForest(
            n_estimators=100, contamination=0.05, random_state=42
        )
        self.model.fit(X)
        joblib.dump(self.model, MODEL_PATH)
        print("[detector.py] Live baseline training complete.")

    def _collect_live_sample(self) -> dict:
        """Collect one row of the server's own current metrics."""
        net = psutil.net_io_counters()
        return {
            "cpu_usage": psutil.cpu_percent(interval=1),
            "ram_usage": psutil.virtual_memory().percent,
            "disk_usage": psutil.disk_usage("/").percent,
            "process_count": len(psutil.pids()),
            "failed_logins": 0,
            "firewall_disabled": 0,
            "network_bytes_sent": net.bytes_sent,
            "network_bytes_recv": net.bytes_recv,
            "usb_connected": 0,
        }

    def load_model(self):
        """Load a previously trained model from disk, if present."""
        if os.path.exists(MODEL_PATH):
            self.model = joblib.load(MODEL_PATH)
            return True
        return False

    def analyze(self, log_entry: dict) -> dict:
        """
        Score a single incoming client log against the trained model
        and translate the result into a human-readable threat report.

        Returns a dict with: threat_level, threat_type, reason,
        confidence_score.
        """
        if self.model is None:
            raise RuntimeError("Model not trained/loaded yet.")

        row = pd.DataFrame([{col: log_entry.get(col, 0) for col in FEATURE_COLUMNS}])

        # decision_function: higher = more normal, lower/negative = more anomalous
        anomaly_score = self.model.decision_function(row)[0]
        is_anomaly = self.model.predict(row)[0] == -1  # -1 means anomaly

        threat_type, reason = self._classify_reason(log_entry)
        threat_level = self._score_to_level(anomaly_score, is_anomaly)

        # Convert the raw anomaly score into an intuitive 0-100 confidence value
        confidence = round(min(max((0.5 - anomaly_score) * 100, 0), 100), 1)

        return {
            "threat_level": threat_level,
            "threat_type": threat_type if is_anomaly else "None",
            "reason": reason if is_anomaly else "Behavior within normal baseline.",
            "confidence_score": confidence,
            "is_anomaly": bool(is_anomaly),
        }

    def _classify_reason(self, log_entry: dict):
        """
        Provide a human-readable reason and rough threat_type label by
        inspecting which specific feature(s) look abnormal. The ML
        model decides IF something is anomalous; this just helps
        explain WHY in plain terms for the dashboard and AI engine.
        """
        cpu = log_entry.get("cpu_usage", 0)
        ram = log_entry.get("ram_usage", 0)
        failed_logins = log_entry.get("failed_logins", 0)
        firewall_disabled = log_entry.get("firewall_disabled", 0)
        net_sent = log_entry.get("network_bytes_sent", 0)
        net_recv = log_entry.get("network_bytes_recv", 0)
        process_count = log_entry.get("process_count", 0)

        if cpu >= 90:
            return "cryptomining", f"Sustained high CPU usage detected ({cpu}%)."
        if failed_logins >= 5:
            return "bruteforce", f"{failed_logins} failed login attempts detected."
        if firewall_disabled:
            return "firewall_disabled", "Firewall was reported as disabled."
        if net_sent > 2_000_000 or net_recv > 2_000_000:
            return "ddos", "Abnormally high network traffic volume detected."
        if ram >= 90:
            return "resource_exhaustion", f"Sustained high RAM usage detected ({ram}%)."
        if process_count > 150:
            return "excessive_processes", f"Unusually high process count ({process_count})."
        return "unknown_anomaly", "Metrics deviate from the learned normal baseline."

    def _score_to_level(self, anomaly_score: float, is_anomaly: bool) -> str:
        """Map the model's continuous anomaly score to a discrete severity label."""
        if not is_anomaly:
            return "Low"
        if anomaly_score < -0.15:
            return "Critical"
        if anomaly_score < -0.05:
            return "High"
        return "Medium"
